In [1]:
import pandas as pd
import numpy as np

data = pd.read_excel('守恒数据_汇总.xlsx', sheet_name='Sheet1')

In [2]:
# grouped = data.groupby(['TASK', 'SUBJIECT'])[['JUDGE_VALUE', 'REASON_VALUE']].sum()
# grouped['SCORE'] = grouped['JUDGE_VALUE'] + grouped['REASON_VALUE']
# grouped.reset_index().pivot_table(index='SUBJIECT',columns='TASK', values = 'SCORE').to_excel('task.xlsx')
# grouped = data.groupby(['GRADE', 'SUBJIECT'])[['JUDGE_VALUE', 'REASON_VALUE']].sum()
# grouped['SCORE'] = grouped['JUDGE_VALUE'] + grouped['REASON_VALUE']
# grouped.reset_index().to_excel('grade.xlsx',index=False)
# grouped = data.groupby(['GENDER', 'SUBJIECT'])[['JUDGE_VALUE', 'REASON_VALUE']].sum()
# grouped['SCORE'] = grouped['JUDGE_VALUE'] + grouped['REASON_VALUE']
# grouped.reset_index().to_excel('gender.xlsx',index=False)
grouped = data.groupby(['GENDER','TASK','SUBJIECT'])[['JUDGE_VALUE', 'REASON_VALUE']].sum()
grouped['SCORE'] = grouped['JUDGE_VALUE'] + grouped['REASON_VALUE']
grouped.reset_index().pivot_table(index=['GENDER', 'SUBJIECT'],columns='TASK', values = 'SCORE').reset_index().to_excel('gender_task.xlsx', index=False)


In [6]:
import scipy.stats as stats

data = [[12, 95, 6, 7],
        [8, 100, 9, 3],
        [2, 77, 26, 15]]

chi2, p, dof, expect = stats.chi2_contingency(data)
print("Chi-squared test statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies table:", expect)

Chi-squared test statistic: 36.12142232946394
p-value: 2.6108068601785803e-06
Degrees of freedom: 6
Expected frequencies table: [[ 7.33333333 90.66666667 13.66666667  8.33333333]
 [ 7.33333333 90.66666667 13.66666667  8.33333333]
 [ 7.33333333 90.66666667 13.66666667  8.33333333]]


In [4]:
grade = data.groupby(['GRADE'])['TYPE'].value_counts().reset_index()
grade.to_excel('grade_type.xlsx', index=False)

In [10]:
grade[grade['GENDER'] == 'F']['REASON_VALUE'].value_counts()

REASON_VALUE
0    19
2     3
1     3
4     2
5     1
6     1
3     1
Name: count, dtype: int64

In [52]:
grade_shouheng = [[1, 3, 16],  # 男性的观察频数
        [0, 5, 15],
        [1, 12, 7]]  # 女性的观察频数
# 执行卡方独立性检验
chi2, p, dof, expected = stats.chi2_contingency(grade_shouheng)
print("Chi-squared test statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected values:", expected)

Chi-squared test statistic: 11.542105263157895
p-value: 0.021101818191112797
Degrees of freedom: 4
Expected values: [[ 0.66666667  6.66666667 12.66666667]
 [ 0.66666667  6.66666667 12.66666667]
 [ 0.66666667  6.66666667 12.66666667]]


In [ ]:
# 根据A和B列进行分组，统计A和B所有条件下JUDGE_VALUE列和REASON_VALUE列所有单元格的和的和
exp = data.groupby(['TASK', 'SUBJIECT'])['REASON_VALUE'].sum().reset_index()


